### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by dtso-i** [Alwaysprogram/MHS-Grade#1]
- [ ] store the data to chrome.storage.local
- [ ] store subject colors
- [ ] popout button: pop out into another page
- [ ] make another html(similar to popup.html)
- [ ] change opennewtab to just open html file
- [ ] filter out repeated data
- [ ] button to refetch data (refresh button)
- [ ] add a loading screen while fetching data from API
- [ ] config button(settings/prefrences)
- [ ]  subject colors
- [ ] color selector
- [ ] chart type
- [ ] report problem button
- [ ] google form
- [ ] add data analysis (analytical computing)
- [ ] talk to Mr. Almena for advertising
- [ ] change to tsc maybe
